title:        Minerva Foundry
tagline:      'A Product Incubator Lead by Strong Ethics'
description:  'Going Up'
url:          http://minervafoundry.com
version:      0.2
author:
  name:       'Minerva Foundry'
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
